// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFx0tv4AFu8HmCne1JwkgMLWT7Im3AXck',
    appId: '1:189845748635:android:5cf13e931e5d95944fbf3e',
    messagingSenderId: '189845748635',
    projectId: 'journalmax-6ca4a',
    storageBucket: 'journalmax-6ca4a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmiw-MgqP1ZUUJLb1V4OzyAeW0eycGDlc',
    appId: '1:189845748635:ios:0645acfadcca64664fbf3e',
    messagingSenderId: '189845748635',
    projectId: 'journalmax-6ca4a',
    storageBucket: 'journalmax-6ca4a.appspot.com',
    androidClientId: '189845748635-1i3gqn4sl6vi5nkl323v2n7c304pqil0.apps.googleusercontent.com',
    iosClientId: '189845748635-jbeau2km9e7p3ev4kmefpu97kuaj9krl.apps.googleusercontent.com',
    iosBundleId: 'com.example.journalMax',
  );
}
